"use client";

import { Pie, PieChart } from "recharts";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/components/ui/chart";

type AreaData = {
  areaName: string;
  total: number;
};

type ProyectosPieChartProps = {
  data: AreaData[];
};

// Color palette
const CHART_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
];

// Slugify area names to use as config keys
function slugify(name: string) {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "");
}

export function ProyectosPieChart({ data }: ProyectosPieChartProps) {
  // Build slug map
  const slugMap = data.map((area, index) => ({
    slug: slugify(area.areaName),
    areaName: area.areaName,
    total: area.total,
    color: CHART_COLORS[index % CHART_COLORS.length],
  }));

  // Transform data for chart — fill must reference CSS var generated by ChartStyle
  const chartData = slugMap.map((item) => ({
    area: item.slug,
    proyectos: item.total,
    fill: `var(--color-${item.slug})`,
  }));

  // Build config — keys must match the values in the "area" field of chartData
  const chartConfig: ChartConfig = {
    proyectos: { label: "Proyectos" },
  };
  for (const item of slugMap) {
    chartConfig[item.slug] = {
      label: item.areaName,
      color: item.color,
    };
  }

  const totalProyectos = data.reduce((sum, area) => sum + area.total, 0);

  return (
    <Card className="flex flex-col">
      <CardHeader className="items-center pb-0">
        <CardTitle>Distribución de Proyectos por Área</CardTitle>
        <CardDescription>Total de {totalProyectos} proyectos</CardDescription>
      </CardHeader>
      <CardContent className="flex-1 pb-0">
        <ChartContainer
          config={chartConfig}
          className="mx-auto aspect-square max-h-[300px] px-0">
          <PieChart>
            <ChartTooltip
              content={<ChartTooltipContent nameKey="area" hideLabel />}
            />
            <Pie
              data={chartData}
              dataKey="proyectos"
              nameKey="area"
              labelLine={false}
              label={({ payload, ...props }) => {
                return (
                  <text
                    cx={props.cx}
                    cy={props.cy}
                    x={props.x}
                    y={props.y}
                    textAnchor={props.textAnchor}
                    dominantBaseline={props.dominantBaseline}
                    fill="hsla(var(--foreground))">
                    {payload.proyectos}
                  </text>
                );
              }}
            />
            <ChartLegend
              content={<ChartLegendContent nameKey="area" />}
              className="-translate-y-2 flex-wrap gap-2 *:basis-1/4 *:justify-center"
            />
          </PieChart>
        </ChartContainer>
      </CardContent>
    </Card>
  );
}
